# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    format_listener:
        rules:
            path: ^/api
            prefer_extension: false
            fallback_format: json
#            priorities: [ json, html ]
#    param_fetcher_listener:  true
    allowed_methods_listener:  true
#    routing_loader: true
    view:
        view_response_listener:  true
        formats:
            json: true
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
        codes:
            App\Exception\BadRequestException: 400
        messages:
            App\Exception\BadRequestException: true
